default-bank:
  bank:
    name: "LLC DefaultBank"
    partner:
      prefix-url: "http://localhost:8080"
server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
    defer-datasource-initialization: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      allow-pool-suspension: true
    driverClassName: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  file:
    name: src/main/resources/application_logs.txt
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
  logback:
    rolling policy:
      max-history: 30
      max-file-size: 10MB

jwt:
  lifetime: 15m
  not-before: 10s
  audience: "online_bank audience"
  issuer: "com.example"
  secret-file-name: ${JWT_SECRET_FILE_NAME}
  refresh-token-life-time: 30d